export type CenterSeed = {
  no: number;
  zone: string;
  center: string;
};

export const CENTER_SEEDS: CenterSeed[] = [
  { no: 1, zone: "Ahmedabad East", center: "Ghanshyamnagar" },
  { no: 2, zone: "Ahmedabad East", center: "Naroda" },
  { no: 3, zone: "Ahmedabad East", center: "Nikol" },
  { no: 4, zone: "Ahmedabad East", center: "Isanpur" },
  { no: 5, zone: "Ahmedabad East", center: "Vastral" },
  { no: 6, zone: "Ahmedabad West", center: "Vasna" },
  { no: 7, zone: "Ahmedabad West", center: "Satellite" },
  { no: 8, zone: "Ahmedabad West", center: "Ghatlodiya" },
  { no: 9, zone: "Ahmedabad West", center: "Gota" },
  { no: 10, zone: "Ahmedabad West", center: "Sanand" },
  { no: 11, zone: "Ahmedabad West", center: "Bavla" },
  { no: 12, zone: "Anand", center: "Anand" },
  { no: 13, zone: "Bhavnagar", center: "Bhavnagar" },
  { no: 14, zone: "Bhavnagar", center: "Una" },
  { no: 15, zone: "Gandhinagar", center: "Chandkheda" },
  { no: 16, zone: "Gandhinagar", center: "Gandhinagar" },
  { no: 17, zone: "Gandhinagar", center: "Kalol" },
  { no: 18, zone: "Gandhinagar", center: "Swaminarayan Dham" },
  { no: 19, zone: "Godhar", center: "Godhar" },
  { no: 20, zone: "Godhar", center: "Santrampur" },
  { no: 21, zone: "Godhar", center: "Virpur" },
  { no: 22, zone: "Godhara", center: "Godhra" },
  { no: 23, zone: "Godhara", center: "Zalod" },
  { no: 24, zone: "Godhara", center: "Dahod" },
  { no: 25, zone: "Godhara", center: "Chhodaudepur" },
  { no: 26, zone: "Himmatnagar", center: "Vijapur" },
  { no: 27, zone: "Himmatnagar", center: "Himmatnagar" },
  { no: 28, zone: "Himmatnagar", center: "Bayad" },
  { no: 29, zone: "Himmatnagar", center: "Modasa" },
  { no: 30, zone: "Himmatnagar", center: "Malpur" },
  { no: 31, zone: "Maharastra", center: "Kandivali" },
  { no: 32, zone: "Maharastra", center: "Navi Mumbai" },
  { no: 33, zone: "Maharastra", center: "Pune" },
  { no: 34, zone: "Mahesana", center: "Mehsana" },
  { no: 35, zone: "Mahesana", center: "Kadi" },
  { no: 36, zone: "Mahesana", center: "Patan" },
  { no: 37, zone: "Mahesana", center: "Unjha" },
  { no: 38, zone: "Mahesana", center: "Palanpur" },
  { no: 39, zone: "Mahesana", center: "Visnagar" },
  { no: 40, zone: "Morbi", center: "Morbi" },
  { no: 41, zone: "Morbi", center: "Bhuj" },
  { no: 42, zone: "Rajkot", center: "Rajkot" },
  { no: 43, zone: "Rajkot", center: "Junagadh" },
  { no: 44, zone: "Surat", center: "Varachha" },
  { no: 45, zone: "Surat", center: "Dabholi" },
  { no: 46, zone: "Surat", center: "Bharuch" },
  { no: 47, zone: "Surat", center: "Ankleshwar" },
  { no: 48, zone: "Surendranagar", center: "Surendranagar" },
  { no: 49, zone: "Surendranagar", center: "Viramgam" },
  { no: 50, zone: "Vadodara", center: "Vadodara" },
  { no: 51, zone: "Vadodara", center: "Halol" },
  { no: 52, zone: "Vadodara", center: "Waghodiya" },
  { no: 53, zone: "SSK Zone", center: "Pujya Santo" },
  { no: 54, zone: "SSK Zone", center: "Pujya Tyagi Mukto" },
  { no: 55, zone: "SSK Zone", center: "Male STK" },
  { no: 56, zone: "SSK Zone", center: "Female STK" },
  { no: 57, zone: "SSK Zone", center: "Male SSP" },
  { no: 58, zone: "SSK Zone", center: "Female SSP" },
  { no: 59, zone: "SSK Zone", center: "Male Chhatralaya" },
  { no: 60, zone: "SSK Zone", center: "Female Chhatralaya" }
];
